# Generated by Django 5.2 on 2025-04-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_teammember_experience_years_teammember_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='education',
            field=models.TextField(blank=True, help_text='Education history and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='personal_contact',
            field=models.CharField(blank=True, help_text='Personal contact details like phone number or WhatsApp', max_length=255, null=True),
        ),
    ]
