# Generated by Django 5.2 on 2025-04-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_teammember_education_teammember_personal_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub username for API integration', max_length=100, null=True),
        ),
    ]
